version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: synapse_server_1
      APP_PORT: $APP_SYNAPSE_PORT
      PROXY_AUTH_ADD: 'false'
    container_name: synapse_app_proxy_1

  server:
    image: >-
      matrixdotorg/synapse:v1.128.0@sha256:5765b7f1bd46b3ded0a59546c8e69b33e57ef6007854791701943f0414557e39
    restart: on-failure
    stop_grace_period: 1m
    entrypoint: bash
    command: >-
      -c './start.py generate && ./start.py migrate_config && \
      echo -e "server_name: matrix.saisesrv.org" >> /data/homeserver.yaml && \
      echo -e "enable_registration_without_verification: true" >> /data/homeserver.yaml && \
      grep -q "port: 8448" /data/homeserver.yaml || echo -e "\n- port: 8448\n  tls: true\n  bind_addresses: [\"::\"]\n  type: http\n  x_forwarded: true\n  resources:\n    - names: [federation]\n      compress: false" >> /data/homeserver.yaml && \
      exec ./start.py'
    volumes:
      - ${APP_DATA_DIR}/data/synapse:/data
    ports:
      - "8008:${APP_SYNAPSE_PORT}"
    environment:
      UID: '1000'
      GID: '1000'
      SYNAPSE_HTTP_PORT: ${APP_SYNAPSE_PORT}
      SYNAPSE_SERVER_NAME: matrix.saisesrv.org
      SYNAPSE_REPORT_STATS: 'yes'
      SYNAPSE_ENABLE_REGISTRATION: 'yes'
      SYNAPSE_NO_TLS: 'yes'
    container_name: synapse_server_1

