version: "3.7"

services:
  server:
    image: matrixdotorg/synapse:v1.128.0@sha256:5765b7f1bd46b3ded0a59546c8e69b33e57ef6007854791701943f0414557e39
    restart: on-failure
    stop_grace_period: 1m
    entrypoint: "bash"
    command: "-c './start.py generate && ./start.py migrate_config && echo -e \"\nenable_registration_without_verification: true\" >> /data/homeserver.yaml && exec ./start.py'"
    volumes:
      - ${APP_DATA_DIR}/data/synapse:/data
    environment:
      UID: "1000"
      GID: "1000"
      SYNAPSE_SERVER_NAME: "matrix.saisesrv.org"
      SYNAPSE_REPORT_STATS: "yes"
      SYNAPSE_ENABLE_REGISTRATION: "yes"
      SYNAPSE_NO_TLS: "yes"
     ports:
      - "8008:8008"
      - "8448:8448"

