version: "3.8"

services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: always
    entrypoint: "bash"
    command: "-c './start.py generate && ./start.py migrate_config && echo -e \"\nenable_registration_without_verification: true\" >> /data/homeserver.yaml && exec ./start.py'"
    environment:
      UID: "1000"
      GID: "1000"
      SYNAPSE_SERVER_NAME: "${APP_HIDDEN_SERVICE}"
      SYNAPSE_REPORT_STATS: "yes"
      SYNAPSE_ENABLE_REGISTRATION: "yes"
      SYNAPSE_NO_TLS: "yes"
    volumes:
      # Mappa una directory locale per mantenere persistenti la configurazione e il database
      - ${APP_DATA_DIR}/data/synapse:/data
    ports:
      # Esponi la porta 8008 per il Client-Server API.
      - "8008:8008"
      # Esponi la porta 8448 per la Federazione (Matrix inter-server)
      - "8448:8448"

